### ISSUE TITLE
Evaluate the rules that were disabled after upgrading to ESLint 8.

### ISSUE THREAD

**Issue by TrevorKarjanis** [ni/javascript-styleguide#112]
There were [rules that were disabled or reconfigured](https://github.com/ni/javascript-styleguide/blob/7c8377c93c5de3f00425c9e51ce1d814b0a44b4c/packages/eslint-config-javascript/index.js#L364) to avoid breaking changes after upgrading to ESLint 8 in #104 . They need to be evaluated for the correct configurations.

**Comment by jattasNI** [comment]
`function-call-argument-newline` with config set to `consistent` seems reasonable. This enforces that function call args should either all be on one line or each be on separate lines. Recommend we enforce this rule.

**Comment by jattasNI** [comment]
We lean towards setting `function-paren-newline` to `multiline`, which requires a new line inside the parens if the parameters are on separate lines. But it would be good to verify in a codebase that there aren't any corner cases we're not thinking about (e.g. arrow functions).

**Comment by jattasNI** [comment]
`grouped-accessor-pairs` seems reasonable. Nobody feels strongly about `getBeforeSet` or `setBeforeGet` so our initial recommendation is not to use either of those options.

**Comment by jattasNI** [comment]
`import/no-import-module-exports` seems reasonable. It enforces that you use only CommonJS imports/exports or ES imports/exports, not a mixture within the same file. Recommend we enforce this rule.

**Comment by jattasNI** [comment]
`import/no-relative-packages` seems reasonable. It enforces no relative path imports of packages (relative path imports of modules are still ok). We don't think anything would be violating it today but it would be good to double check.

**Comment by jattasNI** [comment]
`no-promise-executor-return` seems reasonable. It enforces that the function you pass to `new Promise()` should not return a value (it should call `reject`/`resolve` instead). Recommend we enforce this rule.

**Comment by jattasNI** [comment]
`no-restricted-exports` should remain `off`. Projects can configure it if they have specific export names they want to ban, but there aren't any that we want to ban globally.

**Comment by jattasNI** [comment]
`no-unreachable-loop` seems reasonable. It detects when all code paths within a loop return early, making the loop unnecessary. Recommend we enforce this rule.

**Comment by jattasNI** [comment]
`no-unsafe-optional-chaining` seems reasonable. It detects cases where the `.?` operator might result in `undefined` which isn't being handled. We should also enable `disallowArithmeticOperators` to prevent `NaN` from being accidentally unhandled.

**Comment by jattasNI** [comment]
`no-useless-backreference` sounds reasonable. It prevents useless parts of regular expressions. Recommend we enable it.

**Comment by jattasNI** [comment]
`no-constructor-return` seems reasonable. It prevents you from returning a value from a constructor. Recommend we enable it.

**Comment by jattasNI** [comment]
`no-nonoctal-decimal-escape` seems reasonable. Recommend we enable it.

**Comment by jattasNI** [comment]
`prefer-exponentiation-operator` seems reasonable. In the rare cases where we do exponentiation, prefer a consistent `**` syntax rather than `Math.pow()`. Recommend we enable it.

**Comment by jattasNI** [comment]
`prefer-regex-literals` seems reasonable. We prefer literals over the `RexExp()` constructor. Recommend we enable it.
