### ISSUE TITLE
NI ESLint ruleset for Playwright

### ISSUE THREAD

**Issue by jattasNI** [ni/javascript-styleguide#114]
Several codebases are using Playwright for end-to-end testing. They often depend on [`eslint-plugin-playwright`](https://www.npmjs.com/package/eslint-plugin-playwright) and configure their `eslintrc` like this:
```
           "extends": [
                "@ni/eslint-config-typescript",
                "@ni/eslint-config-typescript/requiring-type-checking",
                "plugin:playwright/playwright-test"
            ],
```

One problem with this configuration is that `playwright/playwright-test` has several rules configured as `warning` but we generally prefer to use `error` or `off` because it prevents lint output from getting noisy with warnings that devs don't bother to fix.

If we publish a Playwright-specific configuration we should also:
1. have it extend `@ni/eslint-config-typescript` so clients don't need to extend as many rulesets. Having it in a separate config from our typescript ruleset would allow it to be targeted to specific files with the `-test.ts` extension. We'd also provide a `eslint-config-playwright-requiring-type-checking` that would be an alias for the existing typescript-requring-type-checking (or decide to get rid of all of our `*-requring-type-checking` rulesets, but that could be done in a separate pass).
2. evaluate rules that aren't part of their recommended ruleset to see if we want to enable them by default (see comments below for our decisions)
3. have a smoke test as we do for other config files
4. update our scripts that evaluate whether the rules have changed
5. update docs
6. evangelize the ruleset to playwright codebases (and/or update [those codebases](https://dev.azure.com/ni/DevCentral/_search?action=contents&text=%40playwright/test%20file%3Apackage.json&type=code&lp=code-Project&filters=ProjectFilters%7BDevCentral%7DRepositoryFilters%7BSkyline%7D&pageSize=25&result=DefaultCollection/DevCentral/Skyline/GBmaster//Web/Workspaces/RoutineManager/acceptance-tests/package.json) ourselves)

**Comment by mure** [comment]
It came up in [this PR](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/419780) that we may want to disable `playwright/no-force-option`.

**Comment by rajsite** [comment]
In meeting went through the [default rule set](https://github.com/playwright-community/eslint-plugin-playwright/blob/91ff782a9175475ef4c061b42e1d50bce4258549/src/index.ts#L28-L40) for `playwright/playwright-test` and came to the following proposals:

no-page-pause: error, seems like a debugging thing and should not be in test
no-element-handle: error, prefer using the locator api
no-eval: change to error, prefer using the locator api and locator evaluate
no-skipped-test: off, having skipped tests is useful, particularly for our e2e tests where workflows require temporarily disabling some tests
no-wait-for-timeout: error, do not do arbitrary waits in tests
no-force-option: error, making it an error to encourage devs to leave a comment describing why force is required
max-nested-describe: error, seems unlikely to hit this case so keeping as an upper bound
no-condition-in-test: error, [rule description was compelling](https://github.com/jest-community/eslint-plugin-jest/blob/9bf5161e7255bff67c4cb542ede8495e91978c0e/docs/rules/no-conditional-in-test.md#disallow-conditional-logic-in-tests-no-conditional-in-test)
no-useless-not: error, minor style improvement that makes assertions read more naturally

**Comment by jattasNI** [comment]
Note for next meeting: in the above list, I believe there were still a few more rules left to evaluate (all the non-default ones).

There has also been a new release of the ruleset ([0.12.0](https://github.com/playwright-community/eslint-plugin-playwright/releases/tag/v0.12.0)) which adds some new rules for us to consider.
