### ISSUE TITLE
Possible new configurations for 'no-unused-vars' to catch more unused function arguments

### ISSUE THREAD

**Issue by jattasNI** [ni/javascript-styleguide#32]
In [this PR](https://dev.azure.com/ni/DevCentral/_git/op-web-portal/pullrequest/156798) I noticed that a change caused a function parameter to be unused. I expected the linter to catch this but it didn't because of our current configuration.
```ts
    // allYAxisSelectedColumns is now unused
    private getSeriesName(scatterSettings: ScatterSettings, allYAxisSelectedColumns: ScatterColumn[], column: ScatterColumn, row: any) {
```

This isn't caught because Airbnb defines [no-unused-vars](https://eslint.org/docs/rules/no-unused-vars.html#options) configuration to `['error', { vars: 'all', args: 'after-used', ignoreRestSiblings: true }]`. The `'after-used'` setting means it will only trigger a violation if the unused variable comes after all the used variables in the signature. The purpose of that configuration is to allow defining callback functions that don't use all the parameters
```js
view.model.login.call(view.model, {
  error: function (model, xhr, options) {
    // if you want to use xhr but not model, you still have to provide model
  }
}
```

I see a few ways we can deal with this:
**Option 1**: Leave things as they are. The gap in coverage for unused parameters is small, not fatal, easy to catch manually

**Option 2**: Change to `args: 'all'` which means that all named arguments must be used. In the callback example above we'd have to suppress the error.

**Option 3**: Use `args: 'all'` with `{ "argsIgnorePattern": "^_" }` to allow unused arguments if their name starts with `_`
```js
function foo(x, _y) {
    return x + 1;
}
```

I'm leaning towards Option 3 myself but want to get the group's opinion before proceeding with it.

**Comment by LukasKall** [comment]
I vote for option 3 as well. The underscore pattern aligns with the TypeScript compiler flags `noUnusedLocals` and `noUnusedParameters`, where you have to prefix unused variables with `_` as well.

**Comment by jattasNI** [comment]
We agreed in person to go with option 3 and provide a custom error message to direct people to use underscores for call back functions @jattasNI to create a PR for this.

Reminder to match other rules which override Airbnb defaults.
