### ISSUE TITLE
@typescript-eslint/no-floating-promises conflicts with no-void

### ISSUE THREAD

**Issue by LukasKall** [ni/javascript-styleguide#43]
The `@ni/eslint-config/typescript-requiring-type-checking` rule set enables [@typescript-eslint/no-floating-promises](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-floating-promises.md) which is in general desired to avoid unhandled promises. In some cases, you want to explicitly mark a promise as intentionally not awaited. You can add `void` to indicate that.

```javascript
void Promise.reject('value');
```

But this conflicts with [no-void](https://eslint.org/docs/rules/no-void), which is enabled as well. It has an option [allowAsStatement](https://eslint.org/docs/rules/no-void#allowasstatement) which allows this use of void and it's suggested by the [@typescript-eslint/no-floating-promises](https://github.com/typescript-eslint/typescript-eslint/blob/v4.25.0/packages/eslint-plugin/docs/rules/no-floating-promises.md#ignorevoid) rule to enable it.
> With this option set to true, and if you are using no-void, you should turn on the allowAsStatement option.

I propose to enable the allowAsStatement option on the no-void rule. We can either do this for all the rule sets (JavaScript and TypeScript), or just for the TypeScript ones. I'm curious what other opinions are.

**Comment by rajsite** [comment]
@LukasKall do you have some example code snippets that show some context about why the promise result should be ignored? We already have one exception listed for Angular tests that rely on [jasminewd2](https://github.com/ni/javascript-styleguide/blob/55785af7da36361729f53beef7093d09cb53add8/typescript-requiring-type-checking.js#L14) listed which results in disabling the rule for tests.

**Comment by LukasKall** [comment]
1. I want to show an error message as a dialog using an async function. But I don't want to wait for the user to confirm the error message.
```typescript
void showErrorMessage(
    'Invalid configuration',
    'Please provide a valid Analysis Automation Procedure configuration.'
);
```
2. When you want to fetch data in an `useEffect` React hook, you have to use an async function. But the `useEffect` hook doesn't accept an async function. So you have to call it inside the hook without awaiting it.
```typescript
useEffect(() => {
    const fetchData = async (): Promise<void> => {
        // doing async calls in here with await
    };
    void fetchData();
}, []);
```
3. Sometimes you want to call an asnyc function in a React/HTML event handler, e.g. `onClick`. But you cannot await it because the event handler doesn't accept an async function.
```typescript
<button
    onClick={(): void => {
        void cancel();
    }}
>
```

In all of this cases, you could use `then()` or `catch()` to handle the promise, but in my case that's not necessary, because errors are either handled inside the called function or I don't care if an error occurred (e.g. in case of `showErrorMessage`).

But anyway, the @typescript-eslint/no-floating-promises rule has an [ignoreVoid](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-floating-promises.md#ignorevoid) option. So in case we want to prevent ignoring promises at all, we should disable this options. And if we want to allow to explicitly mark a promise as intentionally not awaited, we should enable the [allowAsStatement](https://eslint.org/docs/rules/no-void#allowasstatement) option.

**Comment by LukasKall** [comment]
We enabled the rules on another TypeScript Project (no React), a [VS Code extension](https://github.com/ni/vscode-ni-python-dataplugins) in this case, and ran into the same issue. For some promises it doesn't care about the result, but marking it with `void` triggered the `no-void` rule.

**Comment by jschumme** [comment]
I don't see any advantages in the `no-void` rule. If someone actively decides to use the void operator, we should let him. It's a thoughtful decision as you would allow to add an _eslint-ignore_.

**Comment by jattasNI** [comment]
@LukasKall this issue has the votes to proceed. Could you create a PR to close it?
