### ISSUE TITLE
Reevaluate arrow-body-style

### ISSUE THREAD

**Issue by TrevorKarjanis** [ni/javascript-styleguide#47]
The [arrow-body-style](https://eslint.org/docs/rules/arrow-body-style) enforces the brace of arrow functions. Our current configuration is the following.
```json
"arrow-body-style": [
    "error",
    "as-needed",
    {
        "requireReturnForObjectLiteral": false
    }
]
```

I've fought with this twice already just creating a PR for this repository. The "as-needed" option enforces removing brackets if all the function does is return a value, but it's common for that return to have multiple lines if the value is long or complicated. The following are considered incorrect.
```javascript
const longConditionExample = value => {
    return conditionOne(value) && conditionTwo(value) && conditionThree(value) && conditionFour(value);
};
const getDivergedRules = rules => {
    return Object.keys(rules)
        .filter(key => !key.startsWith('@angular-eslint'))
        .filter(key => !configTypescript.rules[key] && !configTypescriptTypechecked.rules[key])
        .reduce((config, key) => {
            config[key] = rules[key];
            return config;
        }, {});
};
```

Instead, the rules expects the developer to use parenthesis.
```javascript
const getDivergedRules = rules => (
    Object.keys(rules)
        .filter(key => !key.startsWith('@angular-eslint'))
        .filter(key => !configTypescript.rules[key] && !configTypescriptTypechecked.rules[key])
        .reduce((config, key) => {
            config[key] = rules[key];
            return config;
        }, {});
);
```

I don't think our developers will find this intuitive. They'll likely only learn it by reading the rule's documentation, but most won't get that far. Therefore, we'll have a lot of developers dealing with this error and learning by word of mouth, because this isn't something that's likely to be addressed in a review unless they disable the rule outright. Brackets are simply the intuitive option, and they're ridiculously similar. Do we really feel enforcing single line arrow functions is necessary enough to introduce this churn?

**Comment by rajsite** [comment]
Some other options that would satisfy the rules besides wrapping parens:
```js
const getDivergedRules = rules => Object.keys(rules)
    .filter(key => !key.startsWith('@angular-eslint'))
    .filter(key => !configTypescript.rules[key] && !configTypescriptTypechecked.rules[key])
    .reduce((config, key) => {
        config[key] = rules[key];
        return config;
    }, {});
```

```js
const longConditionExample = value => conditionOne(value)
    && conditionTwo(value)
    && conditionThree(value)
    && conditionFour(value);
```
While I prefer the examples I have shown over the parens or curlies+return I also don't feel like inconsistency in this case hurts readability. I'm guessing your recommendation is to turn the rule off? Can you add a comment with a specific proposal?

**Comment by TrevorKarjanis** [comment]
Yes, it doesn't look like there are any options that would improve the issue.

**Proposal**
```javascript
'arrow-body-style': 'off'
```

**Comment by rajsite** [comment]
@TrevorKarjanis in your proposal can you include a short description about why we would choose that configuration / diverge from the airbnb config? Seems like what we have generally done for other rules: https://github.com/ni/javascript-styleguide/blob/main/index.js

**Comment by TrevorKarjanis** [comment]
@LukasKall would you like to vote or comment?

**Comment by LukasKall** [comment]
@TrevorKarjanis Yeah, sorry. I voted for your proposal.

**Comment by jattasNI** [comment]
@TrevorKarjanis this is ready for a PR
