### ISSUE TITLE
Re-enable @angular-eslint/template/i18n in angular smoke test

### ISSUE THREAD

**Issue by rajsite** [ni/javascript-styleguide#64]
While integrating beachball an upgrade to the the dependencies caused the smoke test to fail for @angular-eslint/template/i18n.

The rule was disabled for the smoke test and should be re-enabled: https://github.com/ni/javascript-styleguide/blob/5d549a4a9b0377dd3d32e18ea44fc60e27395615/tests/angular/.eslintrc.js#L19

**Comment by rajsite** [comment]
@scotia673 do you know the syntax to make that rule pass in that smoke test? Would love a PR if you know off the top :D (I should learn it eventually but today isn't that day)

**Comment by scotia673** [comment]
I assume this rule is just enforcing that i18n is used here? If so, then I believe the syntax would be `template: 'Hello <span i18n-id [(id)]="name">{{name}}</span>!'`?
