### ISSUE TITLE
Consider allowing ++ and --

### ISSUE THREAD

**Issue by jattasNI** [ni/javascript-styleguide#68]
We [currently enable `no-plusplus`](https://github.com/ni/javascript-styleguide/blob/2eefa5b8f9bd3e68031cdb0e928cd97254a45ba6/packages/eslint-config-javascript/index.js#L197) which bans `++` and `--` (except as the last clause in `for` loops). The [rationale in the rule description](https://eslint.org/docs/rules/no-plusplus) is that automatic semicolon insertion can make these operators ambiguous:
```js
i
++
j
```

However, we currently require semicolons via `semi` and `@typescript-eslint/semi`, so that case shouldn't be possible.

If we allow increment and decrement again are there any other issues that could arise?

**Comment by rajsite** [comment]
My concern was never really the semicolon insertion discussion, that seems a bit contrived. My concern is the subtleties of the prefix/postfix ++ behavior in expressions that do more than modify a value. ie `result = var++` is a tricky pattern where you need to remember the difference between prefix/postfix compared to `result = var +=1` where the ambiguity does not exist.

The old school Crockford jslint description is why I'd prefer to avoid it (despite the usual cantankerous tone lol): https://www.jslint.com/help.html
> The ++ increment and -- decrement operators have been known to contribute to bad code by encouraging excessive trickiness. They are second only to faulty architecture in enabling to viruses and other security menaces. Also, preincrement/postincrement confusion can produce off-by-one errors that are extremely difficult to diagnose. Fortunately, they are also complete unnecessary. There are better ways to add 1 to a variable.
> 
> It is best to avoid these operators entirely and rely on += and -= instead.

**Comment by rajsite** [comment]
Closing from lack of activity, if there is additional feedback we can re-open
