### ISSUE TITLE
Deprecate @ni/eslint-config

### ISSUE THREAD

**Issue by TrevorKarjanis** [ni/javascript-styleguide#74]
To avoid confusion, consider deprecating [@ni/eslint-config](https://www.npmjs.com/package/@ni/eslint-config) and updating the readme to reflect this. Can we eventually de-list it from the npm registry?

**Comment by rajsite** [comment]
Deprecated the package with the following warning:

![image](https://user-images.githubusercontent.com/1588923/148450471-afef41f8-cd1b-482f-b128-c5f48341b484.png)


> The package @ni/eslint-config is deprecated. Please use one of @ni/eslint-config-javascript, @ni/eslint-config-typescript, or @ni/eslint-config-angular instead. See https://www.github.com/ni/javascript-styleguide for more information.
