### ISSUE TITLE
@angular-eslint/template/cyclomatic-complexity is too aggressive

### ISSUE THREAD

**Issue by mollykreis** [ni/javascript-styleguide#95]
I've noticed in a few different changes that the `@angular-eslint/template/cyclomatic-complexity` rule has to be disabled in Angular templates with too many elements containing `*ngIf` statements.

I don't think the rule should cause errors if too many independent (i.e. not nested) elements are conditionally shown/hidden within a component.

[Example component](https://dev.azure.com/ni/DevCentral/_git/Skyline?path=/Web/Workspaces/FileManager/projects/file-manager-lib/src/files/files-toolbar/files-toolbar.component.html)

**Comment by jattasNI** [comment]
We decided to turn off this rule. It triggers when you have lots of `ngIf` statements in a flat hierarchy, which is not something we want to discourage.
@TrevorKarjanis to own turning this decision into a config change.

**Comment by TrevorKarjanis** [comment]
#110
